services:
  archicarmi:
    build: build
    restart: always
    environment:
      APP_DEBUG: ${APP_DEBUG-True}
      NB_WORKERS: ${NB_WORKERS-4}
      SECRET_KEY: ${SECRET_KEY}
      TZ: Europe/Paris
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "8000:8000"
    volumes:
      - ./app:/archicarmi-app
      - ./app/uploaded_files:/uploaded_files
      - ./app/profiles:/profiles
    # command: ["./entrypoint.sh"]
  
    working_dir: /archicarmi-app
    depends_on:
      - db


  ngrok:
  # This service is used for exposing your web application to the internet
    image: wernight/ngrok:latest
    container_name: archicarmi-ngrok
    restart: always
    command: ["ngrok", "http", "http://192.168.1.158:8000"] 
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_REGION: eu
    ports:
      - "4040:4040"
  db:
    image: postgres:16
    container_name: archicarmi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/carmi/backup:/backup

volumes:
  postgres_data:
